
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            # - restore_cache:
            #       keys:
            #           - v1-dependencies-{{ checksum "package.json" }}
            #           - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: cd functions; pwd; npm install
            # - save_cache:
            #       key: v1-npm-deps-{{ checksum "package-lock.json" }}
            #       paths:
            #           - ./functions/node_modules
            - run:
                  name: Install Firebase
                  command: cd functions; pwd; npm install --save-dev firebase-tools
            # - run:
            #       name: Functions Install
            #       command: npm run functions-install
            - run:
                  name: Build
                  command: cd functions; pwd; npm build
            - run:
                  name: Firebase Deploy
                  command: pwd; ./functions/node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only functions
