
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: copy deploy config script to root directory
                command: cp build_scripts/deploy_config.sh deploy_config.sh
            - run:
                name: load in environment variables
                command:  chmod +rwx deploy_config.sh; ./deploy_config.sh                           
            # Download and cache dependencies
            # - restore_cache:
            #       keys:
            #           - v1-dependencies-{{ checksum "package.json" }}
            #           - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: cd functions; pwd; npm install
            # - save_cache:
            #       key: v1-npm-deps-{{ checksum "package-lock.json" }}
            #       paths:
            #           - ./functions/node_modules
            - run:
                  name: Install Firebase
                  command: cd functions; pwd; npm install --save-dev firebase-tools
            - run:
                  name: Build
                  command: cd functions; pwd; npm build
            - run:
                  name: Firebase Deploy
                  command: pwd; ./functions/node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only functions
